FROM python:3.11

WORKDIR /app

COPY ./requirements.txt ./requirements.txt

RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

COPY ./src ./src

# Create migrations 

COPY ./migrations ./migrations

COPY ./alembic.ini ./alembic.ini
COPY ./setup.cfg ./setup.cfg

COPY ./src/entrypoint.sh ./entrypoint.sh
RUN rm ./src/entrypoint.sh

USER root

ENTRYPOINT [ "./entrypoint.sh" ]